FMS/Controllers/DealerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FMS.Models;

namespace FMS.Controllers
{
    public class DealerController : BaseController
    {
        private void PopulateDropDowns(Dealer dealer)
        {
            base.PopulateDropDowns(dealer.Place);

            var depots = db.Depots.Include(d => d.Place);
            int? districtOfficeId = CurrentUser.PlaceId;

            if (districtOfficeId != null)
                depots = depots.Where(o => o.DistrictOfficeId == districtOfficeId);

            ViewBag.DepotId = new SelectList(depots, "DepotId", "Place.Name", dealer.DepotId);
        }

        // GET: Dealer
        public ActionResult Index()
        {
            var dealers = db.Dealers.Include(d => d.Depot).Include(d => d.Place);

            int? districtOfficeId = CurrentUser.PlaceId;

            if (districtOfficeId != null)
                dealers = dealers.Where(o => o.Depot.DistrictOfficeId == districtOfficeId);

            return View(dealers.ToList());
        }

        // GET: Dealer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dealer dealer = db.Dealers.Include(d => d.Depot).Include(d => d.Place).FirstOrDefault(o => o.DealerId == id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            return View(dealer);
        }

        // GET: Dealer/Create
        public ActionResult Create()
        {
            var dealer = new Dealer();
            dealer.Place = new Place();

            PopulateDropDowns(dealer);
            return View(dealer);
        }

        // POST: Dealer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dealer dealer)
        {
            if (ModelState.IsValid)
            {
                AddPlace(dealer.Place, PlaceType.Dealer);
                db.Dealers.Add(dealer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateDropDowns(dealer);
            return View(dealer);
        }

        // GET: Dealer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dealer dealer = db.Dealers.Include(d => d.Depot).Include(d => d.Place).FirstOrDefault(o => o.DealerId == id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            PopulateDropDowns(dealer);
            return View(dealer);
        }

        // POST: Dealer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Dealer dealer)
        {
            if (ModelState.IsValid)
            {
                EditPlace(dealer.Place);
                db.Entry(dealer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateDropDowns(dealer);
            return View(dealer);
        }

        // GET: Dealer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dealer dealer = db.Dealers.Include(d => d.Depot).Include(d => d.Place).FirstOrDefault(o=> o.DealerId == id);
            if (dealer == null)
            {
                return HttpNotFound();
            }
            return View(dealer);
        }

        // POST: Dealer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dealer dealer = db.Dealers.Find(id);
            db.Dealers.Remove(dealer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/FlourMillController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FMS.Models;

namespace FMS.Controllers
{
    public class FlourMillController : BaseController
    {
        private void PopulateDropDowns(FlourMill flourMill)
        {
            base.PopulateDropDowns(flourMill.Place);
            ViewBag.DistrictOfficeId = new SelectList(db.DistrictOffices.Include(f => f.Place), "DistrictOfficeId", "Place.Name", flourMill.DistrictOfficeId);
        }

        // GET: FlourMill
        public ActionResult Index()
        {
            var flourMills = db.FlourMills.Include(f => f.DistrictOffice).Include(f => f.Place);
            return View(flourMills.ToList());
        }

        // GET: FlourMill/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlourMill flourMill = db.FlourMills.Include(f => f.DistrictOffice).Include(f => f.Place).FirstOrDefault(o => o.FlourMillId == id);
            if (flourMill == null)
            {
                return HttpNotFound();
            }
            return View(flourMill);
        }

        // GET: FlourMill/Create
        public ActionResult Create()
        {
            var flourMill = new FlourMill();
            flourMill.Place = new Place();
            PopulateDropDowns(flourMill);

            return View(flourMill);
        }

        // POST: FlourMill/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlourMill flourMill)
        {
            if (ModelState.IsValid)
            {
                AddPlace(flourMill.Place, PlaceType.FlourMill);
                db.FlourMills.Add(flourMill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            PopulateDropDowns(flourMill);
            return View(flourMill);
        }

        // GET: FlourMill/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlourMill flourMill = db.FlourMills.Include(f => f.DistrictOffice).Include(f => f.Place).FirstOrDefault(o => o.FlourMillId == id);
            if (flourMill == null)
            {
                return HttpNotFound();
            }
            PopulateDropDowns(flourMill);
            return View(flourMill);
        }

        // POST: FlourMill/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FlourMill flourMill)
        {
            if (ModelState.IsValid)
            {
                EditPlace(flourMill.Place);
                db.Entry(flourMill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateDropDowns(flourMill);
            return View(flourMill);
        }

        // GET: FlourMill/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlourMill flourMill = db.FlourMills.Include(f => f.DistrictOffice).Include(f => f.Place).FirstOrDefault(o => o.FlourMillId == id);
            if (flourMill == null)
            {
                return HttpNotFound();
            }
            return View(flourMill);
        }

        // POST: FlourMill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FlourMill flourMill = db.FlourMills.Find(id);
            db.FlourMills.Remove(flourMill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Controllers/StorageOfficeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FMS.Models;

namespace FMS.Controllers
{
    public class StorageOfficeController : BaseController
    {
        private void PopulateDropDowns(StorageOffice storageOffice)
        {
            base.PopulateDropDowns(storageOffice.Place);
        }

        // GET: StorageOffice
        public ActionResult Index()
        {
            var storageOffices = db.StorageOffices.Include(s => s.Directorate).Include(s => s.Place);
            return View(storageOffices.ToList());
        }

        // GET: StorageOffice/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StorageOffice storageOffice = db.StorageOffices.Include(o => o.Place).FirstOrDefault(o => o.StorageOfficeId == id);
            if (storageOffice == null)
            {
                return HttpNotFound();
            }
            return View(storageOffice);
        }

        // GET: StorageOffice/Create
        public ActionResult Create()
        {
            var storageOffice = new StorageOffice();
            storageOffice.Place = new Place();

            PopulateDropDowns(storageOffice);
            return View(storageOffice);
        }

        // POST: StorageOffice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StorageOffice storageOffice)
        {
            if (ModelState.IsValid)
            {
                AddPlace(storageOffice.Place, PlaceType.StorageOffice);
                db.StorageOffices.Add(storageOffice);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            PopulateDropDowns(storageOffice);
            return View(storageOffice);
        }

        // GET: StorageOffice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StorageOffice storageOffice = db.StorageOffices.Include(o => o.Place).FirstOrDefault(o => o.StorageOfficeId == id);
            if (storageOffice == null)
            {
                return HttpNotFound();
            }

            PopulateDropDowns(storageOffice);
            return View(storageOffice);
        }

        // POST: StorageOffice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StorageOffice storageOffice)
        {
            if (ModelState.IsValid)
            {
                EditPlace(storageOffice.Place);
                db.Entry(storageOffice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            PopulateDropDowns(storageOffice);
            return View(storageOffice);
        }

        // GET: StorageOffice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StorageOffice storageOffice = db.StorageOffices.Include(o => o.Place).FirstOrDefault(o => o.StorageOfficeId == id);
            if (storageOffice == null)
            {
                return HttpNotFound();
            }
            return View(storageOffice);
        }

        // POST: StorageOffice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StorageOffice storageOffice = db.StorageOffices.Find(id);
            db.StorageOffices.Remove(storageOffice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FMS/Views/CommodityTransaction/Dealer.cshtml
@model IEnumerable<FMS.Models.CommodityTransaction>
@{
    ViewBag.Title = "Dealer Transactions (Flour Sold to Dealer by Depot)";
}

<div class="title">
    @ViewBag.Title
    <div class="float-right">
        @Html.ActionLink("Payments", "DealerPayments", "CashTransaction", null, new { @class = "btn btn-info" })
    </div>
</div>

<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.Type)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CommodityType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DispatchDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReceiveDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bags)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VoucherNo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommodityType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromPlace.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToPlace.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DispatchDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiveDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bags)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VoucherNo)
            </td>
            <td>
                @Html.ActionLink("Print", "PrintVoucher", new { id = item.CommodityTransactionId })
                @*@Html.ActionLink("Payment", "Dealer", "CashTransaction", new { id = item.CommodityTransactionId }, null)
                @Html.Raw("&nbsp;|&nbsp;")
                @Html.ActionLink("Delete", "Delete", new { id = item.CommodityTransactionId })*@
            </td>
        </tr>
    }

</table>

FMS/Views/CommodityTransaction/Delete.cshtml
@model FMS.Models.CommodityTransaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CommodityTransaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CommodityType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommodityType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contractor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contractor.Place.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssuingOfficer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssuingOfficer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromPlace.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceivingOfficer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceivingOfficer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompositeKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompositeKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToPlaceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToPlaceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VoucherNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoucherNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DispatchDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DispatchDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trucks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trucks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FMS/Views/CommodityTransaction/FlourMillDispatch.cshtml
@model FMS.Models.CommodityTransaction
@{
    ViewBag.Title = "Flour Mill Shipments - Dispatch Shipment to Depot";
}

<div class="title">
    @ViewBag.Title
    <div class="float-right">
        @Html.ActionLink("Back to List", "FlourMill", null, new { @class = "btn btn-info" })
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.CommodityTransactionId)
    
    <table class="table2columns">
        <tr>
            <td>
                <div class="form-horizontal">
                    
                    @*<div class="form-group">
                        @Html.LabelFor(model => model.CompositeKey, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.CompositeKey)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   *@
                    <div class="form-group">
                        @Html.LabelFor(model => model.BookNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BookNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BookNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.VoucherNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.VoucherNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.VoucherNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DispatchDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DispatchDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DispatchDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FromPlaceId, "From", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("FromPlaceId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FromPlaceId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ToPlaceId, "To", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ToPlaceId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ToPlaceId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                   <div class="form-group">
                        @Html.LabelFor(model => model.CommodityTypeId, "Commodity Type", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("CommodityTypeId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CommodityTypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Trucks, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Trucks, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Trucks, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Bags, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Bags, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Bags, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UnitId, "Units", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("UnitId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UnitId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </td>
            <td>
                <div class="form-horizontal">

                    @*<div class="form-group">
                        @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.IssuingOfficerId, "Issuing Officer", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("IssuingOfficerId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IssuingOfficerId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ContractorId, "Contractor", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ContractorId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ContractorId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="form-group">
                        @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control", @readonly=true } })
                            @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ReceivingOfficerId, "Receiving Officer", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ReceivingOfficerId", ViewBag.ReceivingOfficerId as SelectList, "-- Select Receiving Officer --", htmlAttributes: new { @class = "form-control", @readonly = true })
                            @Html.ValidationMessageFor(model => model.ReceivingOfficerId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="DISPATCH" class="btn btn-primary" /> | 
                            @Html.ActionLink("Cancel", "FlourMill")
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    </table>


}

<div>
    @Html.ActionLink("Back to List", "FlourMill")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bags")
    <script>
        var getUrl = '@Url.Content("~/CommodityType/List")';
        init(getUrl);
    </script>
@Html.Partial("_PageCloseAlert")
}